### ISSUE TITLE
Can't click button to projects on homePage 2

### ISSUE THREAD

**Issue by Spiderpig02** [CogitoNTNU/web-frontend#26]
The button can not be clicked on homePage 2, I tried to fix it quickly, but the I did not succeed.

**Comment by SverreNystad** [comment]
I found the solution! The issue was resolved by adding pointer-events: none; to the gradient overlay. This CSS rule allows mouse events to pass through the overlay, making underlying elements, like the button, clickable:

```tsx
<div className="absolute w-full h-full bg-gradient-to-b to-transparent from-blue-dark from-0% to-30% z-50 pointer-events-none"></div>
```
This adjustment ensures that the overlay remains visible for styling purposes but does not interfere with the interaction of elements below it.
